version: 2
jobs:
  build:
    docker:
      - image: circleci/phenoSynth:tagname
    steps:
      - checkout
      - run: R --version
  test:
    docker:
      - image: circleci/phenoSynth:tagname
    steps:
      - checkout
      - run: R --version
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
